APP_STL := gnustl_static
APP_CPPFLAGS := -frtti -std=c++11 -Wno-literal-suffix -fsigned-char -Os $(CPPFLAGS)

APP_DEBUG := $(strip $(NDK_DEBUG))
ifeq ($(APP_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif

APP_ABI := armeabi
APP_PLATFORM := android-14
NDK_TOOLCHAIN_VERSION = 4.8

QUICK_CURL_ENABLED := 1
APP_CPPFLAGS += -DQUICK_CURL_ENABLED=1

QUICK_TIFF_ENABLED := 1
APP_CPPFLAGS += -DQUICK_TIFF_ENABLED=1

QUICK_WEBP_ENABLED := 1
APP_CPPFLAGS += -DQUICK_WEBP_ENABLED=1

QUICK_TGA_ENABLED := 1
APP_CPPFLAGS += -DQUICK_TGA_ENABLED=1

QUICK_PHYSICS_ENABLED := 1
APP_CPPFLAGS += -DQUICK_PHYSICS_ENABLED=1

QUICK_NO_WEBSOCKET := 0
APP_CPPFLAGS += -DQUICK_NO_WEBSOCKET=0

QUICK_NO_JSON := 0
APP_CPPFLAGS += -DQUICK_NO_JSON=0

QUICK_NO_SQLITE := 0
APP_CPPFLAGS += -DQUICK_NO_SQLITE=0

QUICK_NO_CCS_ARMATURE := 0
APP_CPPFLAGS += -DQUICK_NO_CCS_ARMATURE=0

QUICK_NO_EXTRA_FILTERS := 0
APP_CPPFLAGS += -DQUICK_NO_EXTRA_FILTERS=0

ifeq ($(QUICK_PHYSICS_ENABLED),1)
APP_CPPFLAGS += -DCC_USE_PHYSICS=1
else
APP_CPPFLAGS += -DCC_USE_PHYSICS=0
endif